/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Usuario
 */
public class Formulario_principal extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_principal
     */
    public Formulario_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_barra_herramientas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_profesor = new javax.swing.JButton();
        jButton_empleado = new javax.swing.JButton();
        jButton_estudiante = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_encabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(800, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_profesor.setBackground(new java.awt.Color(33, 33, 33));
        jButton_profesor.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jButton_profesor.setForeground(new java.awt.Color(245, 245, 245));
        jButton_profesor.setText("Profesor");
        jButton_profesor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_profesorMouseClicked(evt);
            }
        });
        jButton_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_profesorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 150, 50));

        jButton_empleado.setBackground(new java.awt.Color(33, 33, 33));
        jButton_empleado.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jButton_empleado.setForeground(new java.awt.Color(245, 245, 245));
        jButton_empleado.setText("Empleado");
        jButton_empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_empleadoMouseClicked(evt);
            }
        });
        jButton_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, 50));

        jButton_estudiante.setBackground(new java.awt.Color(33, 33, 33));
        jButton_estudiante.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jButton_estudiante.setForeground(new java.awt.Color(245, 245, 245));
        jButton_estudiante.setText("Estudiante");
        jButton_estudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_estudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_estudianteMouseClicked(evt);
            }
        });
        jButton_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_estudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 50));

        jButton_cerrar.setBackground(new java.awt.Color(183, 28, 28));
        jButton_cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 670, 10));

        jLabel_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado.setText("registro de usuarios");
        jLabel_encabezado.setToolTipText("");
        getContentPane().add(jLabel_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_blanco.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_estudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_estudianteActionPerformed

    private void jButton_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_empleadoActionPerformed

    private void jButton_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_profesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_profesorActionPerformed

    private void jButton_estudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_estudianteMouseClicked
       
        Estudiante_form estudiante = new Estudiante_form();
        estudiante.setVisible(true); //Hace la ventana visible
        this.dispose(); //Para que cierre la ventana anterior
    }//GEN-LAST:event_jButton_estudianteMouseClicked

    private void jButton_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_empleadoMouseClicked
        Empleado_form empleado = new Empleado_form();
        empleado.setVisible(true); //Hace la ventana visible
        this.dispose(); //Para que cierre la ventana anterior
    }//GEN-LAST:event_jButton_empleadoMouseClicked

    private void jButton_profesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_profesorMouseClicked
        Profesor_form profesor = new Profesor_form();
        profesor.setVisible(true); //Hace la ventana visible
        this.dispose(); //Para que cierre la ventana anterior
    }//GEN-LAST:event_jButton_profesorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_empleado;
    private javax.swing.JButton jButton_estudiante;
    private javax.swing.JButton jButton_profesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_encabezado;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
