/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu19 = new javax.swing.JMenu();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem16 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem14 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem15 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem13 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem17 = new javax.swing.JCheckBoxMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem68 = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem87 = new javax.swing.JMenuItem();
        jMenuItem88 = new javax.swing.JMenuItem();
        jMenuItem89 = new javax.swing.JMenuItem();
        jMenuItem90 = new javax.swing.JMenuItem();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem92 = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        jMenuItem93 = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        jMenuItem94 = new javax.swing.JMenuItem();
        jMenuItem95 = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jMenuItem96 = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        jMenuItem97 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem98 = new javax.swing.JMenuItem();
        jMenuItem99 = new javax.swing.JMenuItem();
        jMenuItem100 = new javax.swing.JMenuItem();
        jMenuItem101 = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        jMenuItem102 = new javax.swing.JMenuItem();
        jMenuItem103 = new javax.swing.JMenuItem();
        jSeparator29 = new javax.swing.JPopupMenu.Separator();
        jMenuItem104 = new javax.swing.JMenuItem();
        jMenuItem105 = new javax.swing.JMenuItem();
        jMenuItem106 = new javax.swing.JMenuItem();
        jMenuItem107 = new javax.swing.JMenuItem();
        jMenuItem108 = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem117 = new javax.swing.JMenuItem();
        jMenuItem118 = new javax.swing.JMenuItem();
        jMenuItem119 = new javax.swing.JMenuItem();
        jMenuItem120 = new javax.swing.JMenuItem();
        jMenuItem121 = new javax.swing.JMenuItem();
        jMenuItem122 = new javax.swing.JMenuItem();
        jMenuItem110 = new javax.swing.JMenuItem();
        jMenuItem111 = new javax.swing.JMenuItem();
        jMenuItem112 = new javax.swing.JMenuItem();
        jMenuItem113 = new javax.swing.JMenuItem();
        jMenuItem114 = new javax.swing.JMenuItem();
        jMenuItem115 = new javax.swing.JMenuItem();
        jSeparator31 = new javax.swing.JPopupMenu.Separator();
        jMenuItem116 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem109 = new javax.swing.JMenuItem();
        jMenuItem123 = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        jMenuItem124 = new javax.swing.JMenuItem();
        jMenuItem125 = new javax.swing.JMenuItem();
        jSeparator37 = new javax.swing.JPopupMenu.Separator();
        jMenu22 = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jSeparator36 = new javax.swing.JPopupMenu.Separator();
        jMenuItem134 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator34 = new javax.swing.JPopupMenu.Separator();
        jMenuItem126 = new javax.swing.JMenuItem();
        jMenuItem127 = new javax.swing.JMenuItem();
        jMenuItem128 = new javax.swing.JMenuItem();
        jMenuItem129 = new javax.swing.JMenuItem();
        jMenuItem130 = new javax.swing.JMenuItem();
        jMenuItem131 = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        jMenuItem132 = new javax.swing.JMenuItem();
        jMenuItem133 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem135 = new javax.swing.JMenuItem();
        jMenuItem136 = new javax.swing.JMenuItem();
        jMenuItem137 = new javax.swing.JMenuItem();
        jMenuItem138 = new javax.swing.JMenuItem();
        jMenuItem139 = new javax.swing.JMenuItem();
        jSeparator33 = new javax.swing.JPopupMenu.Separator();
        jMenuItem140 = new javax.swing.JMenuItem();
        jMenuItem141 = new javax.swing.JMenuItem();
        jSeparator38 = new javax.swing.JPopupMenu.Separator();
        jMenuItem142 = new javax.swing.JMenuItem();
        jMenuItem143 = new javax.swing.JMenuItem();
        jMenuItem144 = new javax.swing.JMenuItem();
        jMenuItem145 = new javax.swing.JMenuItem();
        jMenuItem146 = new javax.swing.JMenuItem();
        jMenuItem147 = new javax.swing.JMenuItem();
        jSeparator39 = new javax.swing.JPopupMenu.Separator();
        jMenuItem148 = new javax.swing.JMenuItem();
        jMenuItem149 = new javax.swing.JMenuItem();
        jSeparator40 = new javax.swing.JPopupMenu.Separator();
        jMenuItem150 = new javax.swing.JMenuItem();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem156 = new javax.swing.JMenuItem();
        jMenuItem157 = new javax.swing.JMenuItem();
        jSeparator42 = new javax.swing.JPopupMenu.Separator();
        jMenuItem158 = new javax.swing.JMenuItem();
        jSeparator41 = new javax.swing.JPopupMenu.Separator();
        jMenuItem151 = new javax.swing.JMenuItem();
        jMenuItem152 = new javax.swing.JMenuItem();
        jMenuItem153 = new javax.swing.JMenuItem();
        jMenuItem154 = new javax.swing.JMenuItem();
        jMenuItem155 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem159 = new javax.swing.JMenuItem();
        jMenuItem160 = new javax.swing.JMenuItem();
        jMenuItem161 = new javax.swing.JMenuItem();
        jMenuItem162 = new javax.swing.JMenuItem();
        jMenuItem163 = new javax.swing.JMenuItem();
        jMenuItem164 = new javax.swing.JMenuItem();
        jSeparator43 = new javax.swing.JPopupMenu.Separator();
        jMenuItem165 = new javax.swing.JMenuItem();
        jMenuItem166 = new javax.swing.JMenuItem();
        jMenuItem167 = new javax.swing.JMenuItem();
        jSeparator44 = new javax.swing.JPopupMenu.Separator();
        jMenuItem168 = new javax.swing.JMenuItem();
        jMenuItem169 = new javax.swing.JMenuItem();
        jSeparator45 = new javax.swing.JPopupMenu.Separator();
        jMenuItem170 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jSeparator46 = new javax.swing.JPopupMenu.Separator();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem174 = new javax.swing.JMenuItem();
        jMenuItem175 = new javax.swing.JMenuItem();
        jSeparator49 = new javax.swing.JPopupMenu.Separator();
        jMenuItem176 = new javax.swing.JMenuItem();
        jMenuItem177 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem178 = new javax.swing.JMenuItem();
        jMenuItem179 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem180 = new javax.swing.JMenuItem();
        jMenuItem181 = new javax.swing.JMenuItem();
        jSeparator47 = new javax.swing.JPopupMenu.Separator();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem182 = new javax.swing.JMenuItem();
        jMenuItem183 = new javax.swing.JMenuItem();
        jMenuItem171 = new javax.swing.JMenuItem();
        jMenuItem172 = new javax.swing.JMenuItem();
        jSeparator48 = new javax.swing.JPopupMenu.Separator();
        jMenuItem173 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem184 = new javax.swing.JMenuItem();
        jMenuItem185 = new javax.swing.JMenuItem();
        jMenuItem186 = new javax.swing.JMenuItem();
        jSeparator50 = new javax.swing.JPopupMenu.Separator();
        jMenuItem187 = new javax.swing.JMenuItem();
        jMenu31 = new javax.swing.JMenu();
        jMenuItem198 = new javax.swing.JMenuItem();
        jMenuItem199 = new javax.swing.JMenuItem();
        jSeparator54 = new javax.swing.JPopupMenu.Separator();
        jMenuItem200 = new javax.swing.JMenuItem();
        jMenuItem201 = new javax.swing.JMenuItem();
        jSeparator51 = new javax.swing.JPopupMenu.Separator();
        jMenuItem188 = new javax.swing.JMenuItem();
        jMenuItem189 = new javax.swing.JMenuItem();
        jMenuItem190 = new javax.swing.JMenuItem();
        jMenuItem191 = new javax.swing.JMenuItem();
        jMenuItem192 = new javax.swing.JMenuItem();
        jMenuItem193 = new javax.swing.JMenuItem();
        jMenuItem194 = new javax.swing.JMenuItem();
        jMenuItem195 = new javax.swing.JMenuItem();
        jMenu32 = new javax.swing.JMenu();
        jMenuItem202 = new javax.swing.JMenuItem();
        jMenuItem203 = new javax.swing.JMenuItem();
        jSeparator52 = new javax.swing.JPopupMenu.Separator();
        jMenuItem196 = new javax.swing.JMenuItem();
        jSeparator53 = new javax.swing.JPopupMenu.Separator();
        jMenuItem197 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem204 = new javax.swing.JMenuItem();
        jMenuItem205 = new javax.swing.JMenuItem();
        jMenuItem206 = new javax.swing.JMenuItem();
        jMenuItem207 = new javax.swing.JMenuItem();
        jMenuItem209 = new javax.swing.JMenuItem();
        jMenuItem210 = new javax.swing.JMenuItem();
        jMenuItem211 = new javax.swing.JMenuItem();
        jMenuItem212 = new javax.swing.JMenuItem();
        jMenuItem218 = new javax.swing.JMenuItem();
        jMenu34 = new javax.swing.JMenu();
        jMenuItem208 = new javax.swing.JMenuItem();
        jMenuItem219 = new javax.swing.JMenuItem();
        jMenuItem220 = new javax.swing.JMenuItem();
        jMenuItem221 = new javax.swing.JMenuItem();
        jMenuItem222 = new javax.swing.JMenuItem();
        jMenuItem223 = new javax.swing.JMenuItem();
        jMenuItem224 = new javax.swing.JMenuItem();
        jMenuItem225 = new javax.swing.JMenuItem();
        jMenuItem226 = new javax.swing.JMenuItem();
        jMenuItem227 = new javax.swing.JMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem228 = new javax.swing.JMenuItem();
        jMenuItem229 = new javax.swing.JMenuItem();
        jMenu36 = new javax.swing.JMenu();
        jMenuItem230 = new javax.swing.JMenuItem();
        jMenuItem231 = new javax.swing.JMenuItem();
        jMenuItem232 = new javax.swing.JMenuItem();
        jMenuItem233 = new javax.swing.JMenuItem();
        jMenuItem234 = new javax.swing.JMenuItem();
        jMenu37 = new javax.swing.JMenu();
        jMenuItem235 = new javax.swing.JMenuItem();
        jMenuItem236 = new javax.swing.JMenuItem();
        jMenuItem237 = new javax.swing.JMenuItem();
        jMenuItem238 = new javax.swing.JMenuItem();
        jMenuItem239 = new javax.swing.JMenuItem();
        jSeparator57 = new javax.swing.JPopupMenu.Separator();
        jMenuItem240 = new javax.swing.JMenuItem();
        jMenuItem241 = new javax.swing.JMenuItem();
        jMenuItem242 = new javax.swing.JMenuItem();
        jMenuItem243 = new javax.swing.JMenuItem();
        jSeparator55 = new javax.swing.JPopupMenu.Separator();
        jMenu38 = new javax.swing.JMenu();
        jCheckBoxMenuItem18 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem244 = new javax.swing.JMenuItem();
        jMenuItem245 = new javax.swing.JMenuItem();
        jMenuItem246 = new javax.swing.JMenuItem();
        jMenuItem247 = new javax.swing.JMenuItem();
        jMenuItem248 = new javax.swing.JMenuItem();
        jMenuItem249 = new javax.swing.JMenuItem();
        jSeparator58 = new javax.swing.JPopupMenu.Separator();
        jMenuItem250 = new javax.swing.JMenuItem();
        jMenu33 = new javax.swing.JMenu();
        jMenuItem253 = new javax.swing.JMenuItem();
        jMenuItem254 = new javax.swing.JMenuItem();
        jMenuItem255 = new javax.swing.JMenuItem();
        jMenuItem251 = new javax.swing.JMenuItem();
        jMenuItem252 = new javax.swing.JMenuItem();
        jMenuItem213 = new javax.swing.JMenuItem();
        jSeparator56 = new javax.swing.JPopupMenu.Separator();
        jMenuItem214 = new javax.swing.JMenuItem();
        jMenuItem215 = new javax.swing.JMenuItem();
        jMenuItem216 = new javax.swing.JMenuItem();
        jMenu39 = new javax.swing.JMenu();
        jMenuItem256 = new javax.swing.JMenuItem();
        jMenuItem217 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New Project");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("New File");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Open Project");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Open Recent Project");
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Close Other Projects");
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Close All Projects");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Open recent File");
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator2);

        jMenuItem8.setText("Project Groups...");
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Project Properties (Netbeans)");
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator3);

        jMenu14.setText("Import Project");

        jMenuItem39.setText("Eclipse Project...");
        jMenu14.add(jMenuItem39);

        jMenuItem40.setText("Resynchronize Eclipse Projects");
        jMenu14.add(jMenuItem40);

        jMenuItem41.setText("From ZIP...");
        jMenu14.add(jMenuItem41);

        jMenu1.add(jMenu14);

        jMenu15.setText("Export Project");

        jMenuItem10.setText("To ZIP...");
        jMenu15.add(jMenuItem10);

        jMenu1.add(jMenu15);
        jMenu1.add(jSeparator4);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Save");
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("Save As...");
        jMenu1.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Save All");
        jMenu1.add(jMenuItem14);
        jMenu1.add(jSeparator5);

        jMenuItem15.setText("Page Setup...");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Print...");
        jMenu1.add(jMenuItem16);
        jMenu1.add(jSeparator6);

        jMenuItem17.setText("Exit");
        jMenu1.add(jMenuItem17);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem18.setText("Undo");
        jMenu2.add(jMenuItem18);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem19.setText("Redo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);
        jMenu2.add(jSeparator7);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem20.setText("Cut");
        jMenu2.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setText("Copy");
        jMenu2.add(jMenuItem21);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem22.setText("Paste");
        jMenu2.add(jMenuItem22);

        jMenuItem23.setText("Paste Formatted");
        jMenu2.add(jMenuItem23);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setText("Paste from History");
        jMenu2.add(jMenuItem24);

        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setText("Paste as Lines");
        jMenu2.add(jMenuItem25);

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem26.setText("Delete");
        jMenu2.add(jMenuItem26);

        jMenuItem27.setText("Select All");
        jMenu2.add(jMenuItem27);

        jMenuItem28.setText("Select Identifier");
        jMenu2.add(jMenuItem28);
        jMenu2.add(jSeparator8);

        jMenuItem29.setText("Find Selection");
        jMenu2.add(jMenuItem29);

        jMenuItem30.setText("Find Next");
        jMenu2.add(jMenuItem30);

        jMenuItem31.setText("Find Previous");
        jMenu2.add(jMenuItem31);
        jMenu2.add(jSeparator9);

        jMenuItem32.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem32.setText("Find...");
        jMenu2.add(jMenuItem32);

        jMenuItem33.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem33.setText("Replace...");
        jMenu2.add(jMenuItem33);

        jMenuItem34.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem34.setText("Find Usages");
        jMenu2.add(jMenuItem34);
        jMenu2.add(jSeparator10);

        jMenuItem35.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem35.setText("Find in Projects...");
        jMenu2.add(jMenuItem35);

        jMenuItem36.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem36.setText("Replace in Projects...");
        jMenu2.add(jMenuItem36);
        jMenu2.add(jSeparator11);

        jMenuItem37.setText("Start Macro Recording");
        jMenu2.add(jMenuItem37);

        jMenuItem38.setText("Strop Macro Recording");
        jMenu2.add(jMenuItem38);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenu16.setText("Editors");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Source");
        jMenu16.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Design");
        jMenu16.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("History");
        jMenu16.add(jRadioButtonMenuItem3);

        jMenu3.add(jMenu16);

        jMenu17.setText("Split");

        jMenuItem44.setText("Vertically");
        jMenu17.add(jMenuItem44);

        jMenuItem45.setText("Horizontally");
        jMenu17.add(jMenuItem45);

        jMenuItem46.setText("Clear");
        jMenu17.add(jMenuItem46);

        jMenu3.add(jMenu17);

        jMenu18.setText("Code Folds");
        jMenu18.setEnabled(false);
        jMenu3.add(jMenu18);
        jMenu3.add(jSeparator12);

        jMenuItem11.setText("IDE Log");
        jMenu3.add(jMenuItem11);
        jMenu3.add(jSeparator13);

        jMenu19.setText("Toolbars");

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("File");
        jMenu19.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem16.setSelected(true);
        jCheckBoxMenuItem16.setText("Clipboard");
        jMenu19.add(jCheckBoxMenuItem16);

        jCheckBoxMenuItem14.setSelected(true);
        jCheckBoxMenuItem14.setText("Undo/Redo");
        jMenu19.add(jCheckBoxMenuItem14);

        jCheckBoxMenuItem15.setSelected(true);
        jCheckBoxMenuItem15.setText("Run");
        jMenu19.add(jCheckBoxMenuItem15);

        jCheckBoxMenuItem13.setSelected(true);
        jCheckBoxMenuItem13.setText("Debug");
        jMenu19.add(jCheckBoxMenuItem13);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("Performance");
        jMenu19.add(jCheckBoxMenuItem11);
        jMenu19.add(jSeparator15);

        jCheckBoxMenuItem17.setText("Small Tolbar Icons");
        jMenu19.add(jCheckBoxMenuItem17);
        jMenu19.add(jSeparator16);

        jMenuItem42.setText("Reset Toolbars");
        jMenu19.add(jMenuItem42);

        jMenuItem43.setText("Customize");
        jMenu19.add(jMenuItem43);

        jMenu3.add(jMenu19);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Show Editor Toolbar");
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Show Line Numbers");
        jMenu3.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setText("Show Non-Printable Characters");
        jMenu3.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setText("Show Breadcrums");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Show Ident Guide Lines");
        jMenu3.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("Show Diff Sidebar");
        jMenu3.add(jCheckBoxMenuItem6);

        jCheckBoxMenuItem7.setText("Show Versioning Labels");
        jMenu3.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setText("Synchronize Editor with Views");
        jMenu3.add(jCheckBoxMenuItem8);
        jMenu3.add(jSeparator14);

        jCheckBoxMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem9.setText("Show Only Editor");
        jCheckBoxMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem9);

        jCheckBoxMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jCheckBoxMenuItem10.setText("Full Screen");
        jMenu3.add(jCheckBoxMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Navigate");

        jMenuItem47.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem47.setText("Go to File...");
        jMenu4.add(jMenuItem47);

        jMenuItem48.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem48.setText("Go to Type...");
        jMenu4.add(jMenuItem48);

        jMenuItem49.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem49.setText("Go to Symbol...");
        jMenu4.add(jMenuItem49);

        jMenuItem50.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem50.setText("Go to Spring Bean");
        jMenu4.add(jMenuItem50);

        jMenuItem51.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem51.setText("Go to Test/Tested class");
        jMenuItem51.setEnabled(false);
        jMenu4.add(jMenuItem51);

        jMenuItem52.setText("Go to Previous Window");
        jMenu4.add(jMenuItem52);
        jMenu4.add(jSeparator17);

        jMenuItem53.setText("Go to Source");
        jMenuItem53.setEnabled(false);
        jMenu4.add(jMenuItem53);

        jMenuItem54.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem54.setText("Go to Declaration");
        jMenuItem54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem54ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem54);

        jMenuItem55.setText("Go to Super Implementation");
        jMenuItem55.setEnabled(false);
        jMenu4.add(jMenuItem55);

        jMenu20.setText("Inspect");

        jMenuItem68.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem68.setText("Members");
        jMenuItem68.setEnabled(false);
        jMenu20.add(jMenuItem68);
        jMenu20.add(jSeparator22);

        jMenuItem69.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem69.setText("File Members");
        jMenuItem69.setEnabled(false);
        jMenu20.add(jMenuItem69);

        jMenuItem70.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem70.setText("Hierarchy");
        jMenuItem70.setEnabled(false);
        jMenu20.add(jMenuItem70);

        jMenuItem71.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem71.setText("File Hierachy");
        jMenu20.add(jMenuItem71);

        jMenu4.add(jMenu20);
        jMenu4.add(jSeparator18);

        jMenuItem56.setText("Last Edit Location");
        jMenuItem56.setEnabled(false);
        jMenu4.add(jMenuItem56);

        jMenuItem57.setText("Back");
        jMenuItem57.setEnabled(false);
        jMenu4.add(jMenuItem57);

        jMenuItem58.setText("Forward");
        jMenuItem58.setEnabled(false);
        jMenu4.add(jMenuItem58);
        jMenu4.add(jSeparator19);

        jMenuItem59.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem59.setText("Go to Line...");
        jMenuItem59.setEnabled(false);
        jMenu4.add(jMenuItem59);

        jMenuItem60.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem60.setText("Toggle Bookmark");
        jMenu4.add(jMenuItem60);

        jMenuItem61.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PERIOD, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem61.setText("Bookmark History Popup Next");
        jMenu4.add(jMenuItem61);

        jMenuItem62.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem62.setText("Bookmark History popup Previous");
        jMenu4.add(jMenuItem62);
        jMenu4.add(jSeparator20);

        jMenuItem63.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PERIOD, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem63.setText("Next Error");
        jMenuItem63.setEnabled(false);
        jMenu4.add(jMenuItem63);

        jMenuItem64.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem64.setText("Previous Error");
        jMenuItem64.setEnabled(false);
        jMenu4.add(jMenuItem64);
        jMenu4.add(jSeparator21);

        jMenuItem65.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem65.setText("Select in Projects");
        jMenu4.add(jMenuItem65);

        jMenuItem66.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem66.setText("Select in Files");
        jMenu4.add(jMenuItem66);

        jMenuItem67.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem67.setText("Select in Favorites");
        jMenu4.add(jMenuItem67);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Source");

        jMenuItem72.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem72.setText("Format");
        jMenu5.add(jMenuItem72);

        jMenuItem73.setText("Remove Trailing Spaces");
        jMenuItem73.setEnabled(false);
        jMenu5.add(jMenuItem73);

        jMenuItem74.setText("Shift Left");
        jMenuItem74.setEnabled(false);
        jMenu5.add(jMenuItem74);

        jMenuItem75.setText("Shift Right");
        jMenuItem75.setEnabled(false);
        jMenu5.add(jMenuItem75);

        jMenuItem76.setText("Move Up");
        jMenuItem76.setEnabled(false);
        jMenu5.add(jMenuItem76);

        jMenuItem77.setText("Move Down");
        jMenuItem77.setEnabled(false);
        jMenu5.add(jMenuItem77);

        jMenuItem78.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_UP, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem78.setText("Move Code Element Up");
        jMenu5.add(jMenuItem78);

        jMenuItem79.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_DOWN, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem79.setText("Move Code Element Down");
        jMenu5.add(jMenuItem79);

        jMenuItem80.setText("Duplicate Up");
        jMenuItem80.setEnabled(false);
        jMenu5.add(jMenuItem80);

        jMenuItem81.setText("Duplicate Down");
        jMenuItem81.setEnabled(false);
        jMenu5.add(jMenuItem81);

        jMenuItem82.setText("Toggle Comment");
        jMenuItem82.setEnabled(false);
        jMenu5.add(jMenuItem82);
        jMenu5.add(jSeparator23);

        jMenuItem83.setText("Complete Code...");
        jMenuItem83.setEnabled(false);
        jMenu5.add(jMenuItem83);

        jMenuItem84.setText("Insert Code...");
        jMenuItem84.setEnabled(false);
        jMenu5.add(jMenuItem84);

        jMenuItem85.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem85.setText("Remove Surrounding Code...");
        jMenu5.add(jMenuItem85);

        jMenuItem86.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem86.setText("Fix Code...");
        jMenu5.add(jMenuItem86);

        jMenuItem87.setText("Fin Imports...");
        jMenuItem87.setEnabled(false);
        jMenu5.add(jMenuItem87);

        jMenuItem88.setText("Organize Imports");
        jMenu5.add(jMenuItem88);

        jMenuItem89.setText("Organize Members");
        jMenu5.add(jMenuItem89);

        jMenuItem90.setText("Fix Uses...");
        jMenuItem90.setEnabled(false);
        jMenu5.add(jMenuItem90);

        jMenuItem91.setText("Show Method Parameters");
        jMenuItem91.setEnabled(false);
        jMenu5.add(jMenuItem91);

        jMenuItem92.setText("Show Documentation");
        jMenuItem92.setEnabled(false);
        jMenu5.add(jMenuItem92);
        jMenu5.add(jSeparator24);

        jMenuItem93.setText("Make Controller");
        jMenuItem93.setEnabled(false);
        jMenu5.add(jMenuItem93);
        jMenu5.add(jSeparator25);

        jMenuItem94.setText("Insert Next Matching Word");
        jMenuItem94.setEnabled(false);
        jMenu5.add(jMenuItem94);

        jMenuItem95.setText("Insert Previous Matching Word");
        jMenuItem95.setEnabled(false);
        jMenu5.add(jMenuItem95);
        jMenu5.add(jSeparator26);

        jMenuItem96.setText("Inspect...");
        jMenu5.add(jMenuItem96);
        jMenu5.add(jSeparator27);

        jMenuItem97.setText("Scan for External Changes");
        jMenu5.add(jMenuItem97);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Refactor");

        jMenuItem98.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem98.setText("Rename...");
        jMenu6.add(jMenuItem98);

        jMenuItem99.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem99.setText("Move...");
        jMenu6.add(jMenuItem99);

        jMenuItem100.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem100.setText("Copy...");
        jMenu6.add(jMenuItem100);

        jMenuItem101.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem101.setText("Safely Delete...");
        jMenu6.add(jMenuItem101);
        jMenu6.add(jSeparator28);

        jMenuItem102.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem102.setText("Inline...");
        jMenuItem102.setEnabled(false);
        jMenu6.add(jMenuItem102);

        jMenuItem103.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem103.setText("Change Method Parameters...");
        jMenuItem103.setEnabled(false);
        jMenu6.add(jMenuItem103);
        jMenu6.add(jSeparator29);

        jMenuItem104.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem104.setText("Pull Up...");
        jMenu6.add(jMenuItem104);

        jMenuItem105.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem105.setText("Push Down...");
        jMenu6.add(jMenuItem105);

        jMenuItem106.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem106.setText("Extrat Interface...");
        jMenu6.add(jMenuItem106);

        jMenuItem107.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem107.setText("Extrat Superclass...");
        jMenu6.add(jMenuItem107);

        jMenuItem108.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem108.setText("Use Supertype Where Possible...");
        jMenu6.add(jMenuItem108);
        jMenu6.add(jSeparator30);

        jMenu21.setText("Introduce");

        jMenuItem117.setText("Variable...");
        jMenuItem117.setEnabled(false);
        jMenu21.add(jMenuItem117);

        jMenuItem118.setText("Constant...");
        jMenuItem118.setEnabled(false);
        jMenu21.add(jMenuItem118);

        jMenuItem119.setText("Field...");
        jMenuItem119.setEnabled(false);
        jMenu21.add(jMenuItem119);

        jMenuItem120.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem120.setText("Parameter...");
        jMenuItem120.setEnabled(false);
        jMenu21.add(jMenuItem120);

        jMenuItem121.setText("Method...");
        jMenuItem121.setEnabled(false);
        jMenu21.add(jMenuItem121);

        jMenuItem122.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem122.setText("Local extension...");
        jMenuItem122.setEnabled(false);
        jMenu21.add(jMenuItem122);

        jMenu6.add(jMenu21);

        jMenuItem110.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem110.setText("Move Inner to Outer Level...");
        jMenuItem110.setEnabled(false);
        jMenu6.add(jMenuItem110);

        jMenuItem111.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem111.setText("Convert Anonymous to Member...");
        jMenu6.add(jMenuItem111);

        jMenuItem112.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem112.setText("Encapsulate Fields...");
        jMenu6.add(jMenuItem112);

        jMenuItem113.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem113.setText("Replace Constructor with Factory...");
        jMenuItem113.setEnabled(false);
        jMenu6.add(jMenuItem113);

        jMenuItem114.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem114.setText("Replace Constructor with Builder...");
        jMenuItem114.setEnabled(false);
        jMenu6.add(jMenuItem114);

        jMenuItem115.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem115.setText("Invert Boolean...");
        jMenuItem115.setEnabled(false);
        jMenuItem115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem115ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem115);
        jMenu6.add(jSeparator31);

        jMenuItem116.setText("Inspect and Transform...");
        jMenu6.add(jMenuItem116);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Run");

        jMenuItem109.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem109.setText("Run Project (Netbeans)");
        jMenu7.add(jMenuItem109);

        jMenuItem123.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem123.setText("Test Project (Netbeans)");
        jMenu7.add(jMenuItem123);
        jMenu7.add(jSeparator32);

        jMenuItem124.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem124.setText("Build Project (Netbeans)");
        jMenu7.add(jMenuItem124);

        jMenuItem125.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem125.setText("Clean and Build Project (Netbeans)");
        jMenu7.add(jMenuItem125);
        jMenu7.add(jSeparator37);

        jMenu22.setText("Set Project Configuration");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("<default config>");
        jMenu22.add(jRadioButtonMenuItem5);
        jMenu22.add(jSeparator36);

        jMenuItem134.setText("Customize...");
        jMenu22.add(jMenuItem134);

        jMenu7.add(jMenu22);

        jMenu23.setText("Set Project Browser");
        jMenu23.setEnabled(false);
        jMenu7.add(jMenu23);

        jMenu24.setText("Set Main Project");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("None");
        jMenu24.add(jRadioButtonMenuItem4);

        jMenu7.add(jMenu24);
        jMenu7.add(jSeparator34);

        jMenuItem126.setText("Generate Javadoc (Netbeans)");
        jMenu7.add(jMenuItem126);

        jMenuItem127.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem127.setText("Run File");
        jMenu7.add(jMenuItem127);

        jMenuItem128.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem128.setText("Test File");
        jMenuItem128.setEnabled(false);
        jMenu7.add(jMenuItem128);

        jMenuItem129.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem129.setText("Compile File");
        jMenuItem129.setEnabled(false);
        jMenuItem129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem129ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem129);

        jMenuItem130.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem130.setText("Check File");
        jMenuItem130.setEnabled(false);
        jMenu7.add(jMenuItem130);

        jMenuItem131.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem131.setText("Validate File");
        jMenuItem131.setEnabled(false);
        jMenu7.add(jMenuItem131);
        jMenu7.add(jSeparator35);

        jMenuItem132.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem132.setText("Repeat Build/Run: Netbeans (run)");
        jMenu7.add(jMenuItem132);

        jMenuItem133.setText("Strop Build/Run");
        jMenuItem133.setEnabled(false);
        jMenu7.add(jMenuItem133);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Debug");

        jMenuItem135.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem135.setText("Debug Project (Netbeans)");
        jMenu8.add(jMenuItem135);

        jMenuItem136.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem136.setText("Debug File");
        jMenu8.add(jMenuItem136);

        jMenuItem137.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem137.setText("Debug Test File");
        jMenuItem137.setEnabled(false);
        jMenu8.add(jMenuItem137);

        jMenuItem138.setText("Attach Debugger...");
        jMenu8.add(jMenuItem138);

        jMenuItem139.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem139.setText("Finish Debugger Session");
        jMenuItem139.setEnabled(false);
        jMenu8.add(jMenuItem139);
        jMenu8.add(jSeparator33);

        jMenuItem140.setText("Pause");
        jMenuItem140.setEnabled(false);
        jMenu8.add(jMenuItem140);

        jMenuItem141.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem141.setText("Continue");
        jMenuItem141.setEnabled(false);
        jMenu8.add(jMenuItem141);
        jMenu8.add(jSeparator38);

        jMenuItem142.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem142.setText("Step Over");
        jMenuItem142.setEnabled(false);
        jMenu8.add(jMenuItem142);

        jMenuItem143.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem143.setText("Step Over Expression");
        jMenuItem143.setEnabled(false);
        jMenu8.add(jMenuItem143);

        jMenuItem144.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem144.setText("Step Into");
        jMenu8.add(jMenuItem144);

        jMenuItem145.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem145.setText("Step Into Next Method");
        jMenuItem145.setEnabled(false);
        jMenu8.add(jMenuItem145);

        jMenuItem146.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem146.setText("Step Out");
        jMenuItem146.setEnabled(false);
        jMenu8.add(jMenuItem146);

        jMenuItem147.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem147.setText("Run to Cursor");
        jMenuItem147.setEnabled(false);
        jMenu8.add(jMenuItem147);
        jMenu8.add(jSeparator39);

        jMenuItem148.setText("Apply Code Changes");
        jMenuItem148.setEnabled(false);
        jMenu8.add(jMenuItem148);

        jMenuItem149.setText("Take GUI Snapshot");
        jMenuItem149.setEnabled(false);
        jMenu8.add(jMenuItem149);
        jMenu8.add(jSeparator40);

        jMenuItem150.setText("Set Current Thread...");
        jMenuItem150.setEnabled(false);
        jMenu8.add(jMenuItem150);

        jMenu25.setText("Stack");

        jMenuItem156.setText("Make Callee Current");
        jMenuItem156.setEnabled(false);
        jMenu25.add(jMenuItem156);

        jMenuItem157.setText("Make Caller Current");
        jMenuItem157.setEnabled(false);
        jMenu25.add(jMenuItem157);
        jMenu25.add(jSeparator42);

        jMenuItem158.setText("Pop TopMost Call");
        jMenuItem158.setEnabled(false);
        jMenu25.add(jMenuItem158);

        jMenu8.add(jMenu25);
        jMenu8.add(jSeparator41);

        jMenuItem151.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem151.setText("Toggle Line Breakpoint");
        jMenuItem151.setEnabled(false);
        jMenu8.add(jMenuItem151);

        jMenuItem152.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem152.setText("New Breakpoint...");
        jMenu8.add(jMenuItem152);

        jMenuItem153.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem153.setText("New Watch...");
        jMenu8.add(jMenuItem153);

        jMenuItem154.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem154.setText("Evaluate Expression...");
        jMenuItem154.setEnabled(false);
        jMenu8.add(jMenuItem154);

        jMenuItem155.setText("Check for Deadlock");
        jMenuItem155.setEnabled(false);
        jMenu8.add(jMenuItem155);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Profile");

        jMenuItem159.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem159.setText("Profile Project (Netbeans)");
        jMenu9.add(jMenuItem159);

        jMenuItem160.setText("Profile File");
        jMenu9.add(jMenuItem160);

        jMenuItem161.setText("Profile Test File");
        jMenuItem161.setEnabled(false);
        jMenu9.add(jMenuItem161);

        jMenuItem162.setText("Attach to Project (Netbeans)");
        jMenu9.add(jMenuItem162);

        jMenuItem163.setText("Attach to External Process");
        jMenu9.add(jMenuItem163);

        jMenuItem164.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem164.setText("Finish Profiler Session");
        jMenuItem164.setEnabled(false);
        jMenu9.add(jMenuItem164);
        jMenu9.add(jSeparator43);

        jMenuItem165.setText("Take Thread Drump");
        jMenuItem165.setEnabled(false);
        jMenu9.add(jMenuItem165);

        jMenuItem166.setText("Take Heap Drump...");
        jMenuItem166.setEnabled(false);
        jMenu9.add(jMenuItem166);

        jMenuItem167.setText("Run GC");
        jMenuItem167.setEnabled(false);
        jMenu9.add(jMenuItem167);
        jMenu9.add(jSeparator44);

        jMenuItem168.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem168.setText("Take SnapShot of Collected Results");
        jMenuItem168.setEnabled(false);
        jMenu9.add(jMenuItem168);

        jMenuItem169.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem169.setText("Reset Collected Results");
        jMenuItem169.setEnabled(false);
        jMenu9.add(jMenuItem169);
        jMenu9.add(jSeparator45);

        jMenuItem170.setText("Insert Profiling Point...");
        jMenu9.add(jMenuItem170);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Team");

        jMenu26.setText("Shelve Changes");
        jMenu26.setEnabled(false);
        jMenu10.add(jMenu26);
        jMenu10.add(jSeparator46);

        jMenu27.setText("Git");

        jMenuItem174.setText("Clone...");
        jMenu27.add(jMenuItem174);

        jMenuItem175.setText("Initialize Repository...");
        jMenu27.add(jMenuItem175);
        jMenu27.add(jSeparator49);

        jMenuItem176.setText("Repository Browser");
        jMenu27.add(jMenuItem176);

        jMenuItem177.setText("Open Global Configuration");
        jMenu27.add(jMenuItem177);

        jMenu10.add(jMenu27);

        jMenu28.setText("Mercurial");

        jMenuItem178.setText("Initialize Repository...");
        jMenu28.add(jMenuItem178);

        jMenuItem179.setText("Clone Other...");
        jMenu28.add(jMenuItem179);

        jMenu10.add(jMenu28);

        jMenu29.setText("Subversion");

        jMenuItem180.setText("Checkout...");
        jMenu29.add(jMenuItem180);

        jMenuItem181.setText("Import into Repository...");
        jMenu29.add(jMenuItem181);

        jMenu10.add(jMenu29);
        jMenu10.add(jSeparator47);

        jMenu30.setText("History");

        jMenuItem182.setText("Show History");
        jMenu30.add(jMenuItem182);

        jMenuItem183.setText("Revert Deleted");
        jMenuItem183.setEnabled(false);
        jMenu30.add(jMenuItem183);

        jMenu10.add(jMenu30);

        jMenuItem171.setText("Find Tasks...");
        jMenu10.add(jMenuItem171);

        jMenuItem172.setText("Report Task...");
        jMenu10.add(jMenuItem172);
        jMenu10.add(jSeparator48);

        jMenuItem173.setText("Creae Build Job...");
        jMenu10.add(jMenuItem173);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Tools");

        jMenuItem184.setText("Apply Diff Patch...");
        jMenu11.add(jMenuItem184);

        jMenuItem185.setText("Diff...");
        jMenu11.add(jMenuItem185);

        jMenuItem186.setText("Add to Favorites");
        jMenu11.add(jMenuItem186);
        jMenu11.add(jSeparator50);

        jMenuItem187.setText("Analyze Javadoc");
        jMenu11.add(jMenuItem187);

        jMenu31.setText("Internationalization");

        jMenuItem198.setText("Internationalize...");
        jMenu31.add(jMenuItem198);

        jMenuItem199.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem199.setText("Insert Internationalized String...");
        jMenu31.add(jMenuItem199);
        jMenu31.add(jSeparator54);

        jMenuItem200.setText("Internationalization Wizard");
        jMenuItem200.setEnabled(false);
        jMenu31.add(jMenuItem200);

        jMenuItem201.setText("Internationalization Test Wizard");
        jMenu31.add(jMenuItem201);

        jMenu11.add(jMenu31);
        jMenu11.add(jSeparator51);

        jMenuItem188.setText("Java Platforms");
        jMenu11.add(jMenuItem188);

        jMenuItem189.setText("NetBeans Platforms");
        jMenu11.add(jMenuItem189);

        jMenuItem190.setText("Ant Variables");
        jMenu11.add(jMenuItem190);

        jMenuItem191.setText("Libraries");
        jMenu11.add(jMenuItem191);

        jMenuItem192.setText("Servers");
        jMenu11.add(jMenuItem192);

        jMenuItem193.setText("Cloud Providers");
        jMenu11.add(jMenuItem193);

        jMenuItem194.setText("Templates");
        jMenu11.add(jMenuItem194);

        jMenuItem195.setText("DTDs and XML Schemas");
        jMenu11.add(jMenuItem195);

        jMenu32.setText("Palette");

        jMenuItem202.setText("Swing/AWT Components");
        jMenu32.add(jMenuItem202);

        jMenuItem203.setText("Code Clips");
        jMenu32.add(jMenuItem203);

        jMenu11.add(jMenu32);
        jMenu11.add(jSeparator52);

        jMenuItem196.setText("Plugins");
        jMenu11.add(jMenuItem196);
        jMenu11.add(jSeparator53);

        jMenuItem197.setText("Options");
        jMenu11.add(jMenuItem197);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("Windows");

        jMenuItem204.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem204.setText("Projects");
        jMenu12.add(jMenuItem204);

        jMenuItem205.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem205.setText("Files");
        jMenu12.add(jMenuItem205);

        jMenuItem206.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem206.setText("Favorites");
        jMenu12.add(jMenuItem206);

        jMenuItem207.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem207.setText("Services");
        jMenu12.add(jMenuItem207);

        jMenuItem209.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem209.setText("Navigator");
        jMenu12.add(jMenuItem209);

        jMenuItem210.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem210.setText("Action Items");
        jMenu12.add(jMenuItem210);

        jMenuItem211.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem211.setText("Tasks");
        jMenu12.add(jMenuItem211);

        jMenuItem212.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem212.setText("Output");
        jMenuItem212.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem212ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem212);

        jMenuItem218.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem218.setText("Editor");
        jMenu12.add(jMenuItem218);

        jMenu34.setText("Debugging");

        jMenuItem208.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem208.setText("Variables");
        jMenu34.add(jMenuItem208);

        jMenuItem219.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem219.setText("Watches");
        jMenuItem219.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem219ActionPerformed(evt);
            }
        });
        jMenu34.add(jMenuItem219);

        jMenuItem220.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem220.setText("Call Stack");
        jMenu34.add(jMenuItem220);

        jMenuItem221.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem221.setText("Loaded Classes");
        jMenu34.add(jMenuItem221);

        jMenuItem222.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem222.setText("Breakpoints");
        jMenu34.add(jMenuItem222);

        jMenuItem223.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem223.setText("Sessions");
        jMenu34.add(jMenuItem223);

        jMenuItem224.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem224.setText("Threads");
        jMenu34.add(jMenuItem224);

        jMenuItem225.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem225.setText("Sources");
        jMenu34.add(jMenuItem225);

        jMenuItem226.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem226.setText("Debugging");
        jMenu34.add(jMenuItem226);

        jMenuItem227.setText("Analyze Stack");
        jMenu34.add(jMenuItem227);

        jMenu12.add(jMenu34);

        jMenu35.setText("Profiling");

        jMenuItem228.setText("Snapshots");
        jMenu35.add(jMenuItem228);

        jMenuItem229.setText("Profiling Points");
        jMenu35.add(jMenuItem229);

        jMenu12.add(jMenu35);

        jMenu36.setText("Web");

        jMenuItem230.setText("Web Browser");
        jMenu36.add(jMenuItem230);

        jMenuItem231.setText("CSS Styles");
        jMenuItem231.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem231ActionPerformed(evt);
            }
        });
        jMenu36.add(jMenuItem231);

        jMenuItem232.setText("Browser DOM");
        jMenu36.add(jMenuItem232);

        jMenuItem233.setText("Knockout");
        jMenu36.add(jMenuItem233);

        jMenuItem234.setText("Network Monitor");
        jMenu36.add(jMenuItem234);

        jMenu12.add(jMenu36);

        jMenu37.setText("IDE Tools");

        jMenuItem235.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem235.setText("Palette");
        jMenu37.add(jMenuItem235);

        jMenuItem236.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem236.setText("Properties");
        jMenu37.add(jMenuItem236);

        jMenuItem237.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem237.setText("Test Results");
        jMenu37.add(jMenuItem237);

        jMenuItem238.setText("BookMarks");
        jMenu37.add(jMenuItem238);

        jMenuItem239.setText("Javadoc Documentation");
        jMenu37.add(jMenuItem239);
        jMenu37.add(jSeparator57);

        jMenuItem240.setText("Notifications");
        jMenu37.add(jMenuItem240);

        jMenuItem241.setText("Exception Reporter");
        jMenu37.add(jMenuItem241);

        jMenuItem242.setText("Terminal");
        jMenu37.add(jMenuItem242);

        jMenuItem243.setText("Processes");
        jMenuItem243.setEnabled(false);
        jMenu37.add(jMenuItem243);

        jMenu12.add(jMenu37);
        jMenu12.add(jSeparator55);

        jMenu38.setText("Configure Window");

        jCheckBoxMenuItem18.setText("Maximize");
        jMenu38.add(jCheckBoxMenuItem18);

        jMenuItem244.setText("Float");
        jMenu38.add(jMenuItem244);

        jMenuItem245.setText("Float Group");
        jMenu38.add(jMenuItem245);

        jMenuItem246.setText("Minimize");
        jMenu38.add(jMenuItem246);

        jMenuItem247.setText("Minimize Group");
        jMenu38.add(jMenuItem247);

        jMenuItem248.setText("Dock");
        jMenu38.add(jMenuItem248);

        jMenuItem249.setText("Dock Group");
        jMenu38.add(jMenuItem249);
        jMenu38.add(jSeparator58);

        jMenuItem250.setText("Clone Document");
        jMenu38.add(jMenuItem250);

        jMenu33.setText("Split Document");

        jMenuItem253.setText("Vertically");
        jMenu33.add(jMenuItem253);

        jMenuItem254.setText("Horizontally");
        jMenu33.add(jMenuItem254);

        jMenuItem255.setText("Clear");
        jMenuItem255.setEnabled(false);
        jMenu33.add(jMenuItem255);

        jMenu38.add(jMenu33);

        jMenuItem251.setText("New Document Tab Group");
        jMenu38.add(jMenuItem251);

        jMenuItem252.setText("Collapse Document Tab Group");
        jMenu38.add(jMenuItem252);

        jMenu12.add(jMenu38);

        jMenuItem213.setText("Reset Windows");
        jMenu12.add(jMenuItem213);
        jMenu12.add(jSeparator56);

        jMenuItem214.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem214.setText("Close Window");
        jMenu12.add(jMenuItem214);

        jMenuItem215.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem215.setText("Close All Documents");
        jMenu12.add(jMenuItem215);

        jMenuItem216.setText("Close Other Documents");
        jMenu12.add(jMenuItem216);

        jMenu39.setText("Document Groups");

        jMenuItem256.setText("New Document Group");
        jMenu39.add(jMenuItem256);

        jMenu12.add(jMenu39);

        jMenuItem217.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem217.setText("Documents...");
        jMenu12.add(jMenuItem217);

        jMenuBar1.add(jMenu12);

        jMenu13.setText("Help");
        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jCheckBoxMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem9ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jMenuItem54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem54ActionPerformed

    private void jMenuItem115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem115ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem115ActionPerformed

    private void jMenuItem129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem129ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem129ActionPerformed

    private void jMenuItem212ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem212ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem212ActionPerformed

    private void jMenuItem219ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem219ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem219ActionPerformed

    private void jMenuItem231ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem231ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem231ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem13;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem14;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem15;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem16;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem17;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem18;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem100;
    private javax.swing.JMenuItem jMenuItem101;
    private javax.swing.JMenuItem jMenuItem102;
    private javax.swing.JMenuItem jMenuItem103;
    private javax.swing.JMenuItem jMenuItem104;
    private javax.swing.JMenuItem jMenuItem105;
    private javax.swing.JMenuItem jMenuItem106;
    private javax.swing.JMenuItem jMenuItem107;
    private javax.swing.JMenuItem jMenuItem108;
    private javax.swing.JMenuItem jMenuItem109;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem110;
    private javax.swing.JMenuItem jMenuItem111;
    private javax.swing.JMenuItem jMenuItem112;
    private javax.swing.JMenuItem jMenuItem113;
    private javax.swing.JMenuItem jMenuItem114;
    private javax.swing.JMenuItem jMenuItem115;
    private javax.swing.JMenuItem jMenuItem116;
    private javax.swing.JMenuItem jMenuItem117;
    private javax.swing.JMenuItem jMenuItem118;
    private javax.swing.JMenuItem jMenuItem119;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem120;
    private javax.swing.JMenuItem jMenuItem121;
    private javax.swing.JMenuItem jMenuItem122;
    private javax.swing.JMenuItem jMenuItem123;
    private javax.swing.JMenuItem jMenuItem124;
    private javax.swing.JMenuItem jMenuItem125;
    private javax.swing.JMenuItem jMenuItem126;
    private javax.swing.JMenuItem jMenuItem127;
    private javax.swing.JMenuItem jMenuItem128;
    private javax.swing.JMenuItem jMenuItem129;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem130;
    private javax.swing.JMenuItem jMenuItem131;
    private javax.swing.JMenuItem jMenuItem132;
    private javax.swing.JMenuItem jMenuItem133;
    private javax.swing.JMenuItem jMenuItem134;
    private javax.swing.JMenuItem jMenuItem135;
    private javax.swing.JMenuItem jMenuItem136;
    private javax.swing.JMenuItem jMenuItem137;
    private javax.swing.JMenuItem jMenuItem138;
    private javax.swing.JMenuItem jMenuItem139;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem140;
    private javax.swing.JMenuItem jMenuItem141;
    private javax.swing.JMenuItem jMenuItem142;
    private javax.swing.JMenuItem jMenuItem143;
    private javax.swing.JMenuItem jMenuItem144;
    private javax.swing.JMenuItem jMenuItem145;
    private javax.swing.JMenuItem jMenuItem146;
    private javax.swing.JMenuItem jMenuItem147;
    private javax.swing.JMenuItem jMenuItem148;
    private javax.swing.JMenuItem jMenuItem149;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem150;
    private javax.swing.JMenuItem jMenuItem151;
    private javax.swing.JMenuItem jMenuItem152;
    private javax.swing.JMenuItem jMenuItem153;
    private javax.swing.JMenuItem jMenuItem154;
    private javax.swing.JMenuItem jMenuItem155;
    private javax.swing.JMenuItem jMenuItem156;
    private javax.swing.JMenuItem jMenuItem157;
    private javax.swing.JMenuItem jMenuItem158;
    private javax.swing.JMenuItem jMenuItem159;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem160;
    private javax.swing.JMenuItem jMenuItem161;
    private javax.swing.JMenuItem jMenuItem162;
    private javax.swing.JMenuItem jMenuItem163;
    private javax.swing.JMenuItem jMenuItem164;
    private javax.swing.JMenuItem jMenuItem165;
    private javax.swing.JMenuItem jMenuItem166;
    private javax.swing.JMenuItem jMenuItem167;
    private javax.swing.JMenuItem jMenuItem168;
    private javax.swing.JMenuItem jMenuItem169;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem170;
    private javax.swing.JMenuItem jMenuItem171;
    private javax.swing.JMenuItem jMenuItem172;
    private javax.swing.JMenuItem jMenuItem173;
    private javax.swing.JMenuItem jMenuItem174;
    private javax.swing.JMenuItem jMenuItem175;
    private javax.swing.JMenuItem jMenuItem176;
    private javax.swing.JMenuItem jMenuItem177;
    private javax.swing.JMenuItem jMenuItem178;
    private javax.swing.JMenuItem jMenuItem179;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem180;
    private javax.swing.JMenuItem jMenuItem181;
    private javax.swing.JMenuItem jMenuItem182;
    private javax.swing.JMenuItem jMenuItem183;
    private javax.swing.JMenuItem jMenuItem184;
    private javax.swing.JMenuItem jMenuItem185;
    private javax.swing.JMenuItem jMenuItem186;
    private javax.swing.JMenuItem jMenuItem187;
    private javax.swing.JMenuItem jMenuItem188;
    private javax.swing.JMenuItem jMenuItem189;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem190;
    private javax.swing.JMenuItem jMenuItem191;
    private javax.swing.JMenuItem jMenuItem192;
    private javax.swing.JMenuItem jMenuItem193;
    private javax.swing.JMenuItem jMenuItem194;
    private javax.swing.JMenuItem jMenuItem195;
    private javax.swing.JMenuItem jMenuItem196;
    private javax.swing.JMenuItem jMenuItem197;
    private javax.swing.JMenuItem jMenuItem198;
    private javax.swing.JMenuItem jMenuItem199;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem200;
    private javax.swing.JMenuItem jMenuItem201;
    private javax.swing.JMenuItem jMenuItem202;
    private javax.swing.JMenuItem jMenuItem203;
    private javax.swing.JMenuItem jMenuItem204;
    private javax.swing.JMenuItem jMenuItem205;
    private javax.swing.JMenuItem jMenuItem206;
    private javax.swing.JMenuItem jMenuItem207;
    private javax.swing.JMenuItem jMenuItem208;
    private javax.swing.JMenuItem jMenuItem209;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem210;
    private javax.swing.JMenuItem jMenuItem211;
    private javax.swing.JMenuItem jMenuItem212;
    private javax.swing.JMenuItem jMenuItem213;
    private javax.swing.JMenuItem jMenuItem214;
    private javax.swing.JMenuItem jMenuItem215;
    private javax.swing.JMenuItem jMenuItem216;
    private javax.swing.JMenuItem jMenuItem217;
    private javax.swing.JMenuItem jMenuItem218;
    private javax.swing.JMenuItem jMenuItem219;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem220;
    private javax.swing.JMenuItem jMenuItem221;
    private javax.swing.JMenuItem jMenuItem222;
    private javax.swing.JMenuItem jMenuItem223;
    private javax.swing.JMenuItem jMenuItem224;
    private javax.swing.JMenuItem jMenuItem225;
    private javax.swing.JMenuItem jMenuItem226;
    private javax.swing.JMenuItem jMenuItem227;
    private javax.swing.JMenuItem jMenuItem228;
    private javax.swing.JMenuItem jMenuItem229;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem230;
    private javax.swing.JMenuItem jMenuItem231;
    private javax.swing.JMenuItem jMenuItem232;
    private javax.swing.JMenuItem jMenuItem233;
    private javax.swing.JMenuItem jMenuItem234;
    private javax.swing.JMenuItem jMenuItem235;
    private javax.swing.JMenuItem jMenuItem236;
    private javax.swing.JMenuItem jMenuItem237;
    private javax.swing.JMenuItem jMenuItem238;
    private javax.swing.JMenuItem jMenuItem239;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem240;
    private javax.swing.JMenuItem jMenuItem241;
    private javax.swing.JMenuItem jMenuItem242;
    private javax.swing.JMenuItem jMenuItem243;
    private javax.swing.JMenuItem jMenuItem244;
    private javax.swing.JMenuItem jMenuItem245;
    private javax.swing.JMenuItem jMenuItem246;
    private javax.swing.JMenuItem jMenuItem247;
    private javax.swing.JMenuItem jMenuItem248;
    private javax.swing.JMenuItem jMenuItem249;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem250;
    private javax.swing.JMenuItem jMenuItem251;
    private javax.swing.JMenuItem jMenuItem252;
    private javax.swing.JMenuItem jMenuItem253;
    private javax.swing.JMenuItem jMenuItem254;
    private javax.swing.JMenuItem jMenuItem255;
    private javax.swing.JMenuItem jMenuItem256;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem90;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JMenuItem jMenuItem92;
    private javax.swing.JMenuItem jMenuItem93;
    private javax.swing.JMenuItem jMenuItem94;
    private javax.swing.JMenuItem jMenuItem95;
    private javax.swing.JMenuItem jMenuItem96;
    private javax.swing.JMenuItem jMenuItem97;
    private javax.swing.JMenuItem jMenuItem98;
    private javax.swing.JMenuItem jMenuItem99;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator31;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JPopupMenu.Separator jSeparator33;
    private javax.swing.JPopupMenu.Separator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator36;
    private javax.swing.JPopupMenu.Separator jSeparator37;
    private javax.swing.JPopupMenu.Separator jSeparator38;
    private javax.swing.JPopupMenu.Separator jSeparator39;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator40;
    private javax.swing.JPopupMenu.Separator jSeparator41;
    private javax.swing.JPopupMenu.Separator jSeparator42;
    private javax.swing.JPopupMenu.Separator jSeparator43;
    private javax.swing.JPopupMenu.Separator jSeparator44;
    private javax.swing.JPopupMenu.Separator jSeparator45;
    private javax.swing.JPopupMenu.Separator jSeparator46;
    private javax.swing.JPopupMenu.Separator jSeparator47;
    private javax.swing.JPopupMenu.Separator jSeparator48;
    private javax.swing.JPopupMenu.Separator jSeparator49;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator50;
    private javax.swing.JPopupMenu.Separator jSeparator51;
    private javax.swing.JPopupMenu.Separator jSeparator52;
    private javax.swing.JPopupMenu.Separator jSeparator53;
    private javax.swing.JPopupMenu.Separator jSeparator54;
    private javax.swing.JPopupMenu.Separator jSeparator55;
    private javax.swing.JPopupMenu.Separator jSeparator56;
    private javax.swing.JPopupMenu.Separator jSeparator57;
    private javax.swing.JPopupMenu.Separator jSeparator58;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
